### PR TITLE
Add tests for type_support functions

### PR DESCRIPTION
**Pull request by brawner**
Adding unit tests to cover the packages public API as part of the effort to bring these packages to QL 1.

### CODE REVIEW

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10132/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5699/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8234/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10026/)
* Coverage [Build Status](https://ci.ros2.org/job/ci_linux_coverage/80/)

**Comment by brawner** [comment]
This is ready for review

**Comment by brawner** [comment]
Coverage test is unstable because I forgot to run uncrustify before running it. Otherwise coverage is now at 94%!

**Comment by brawner** [comment]
I have some work to do on Windows looks like:
[Build Status](https://ci.ros2.org/job/ci_windows/10058/)

**Comment by brawner** [comment]
Windows should be working now.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10258/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5797/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8339/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10143/)

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10752/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6147/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8754/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10641/)

**Comment by ahcorde** [comment]
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10648/)

**Comment by brawner** [comment]
Trying to fix windows warning:
[Build Status](https://ci.ros2.org/job/ci_windows/10653/)

**Comment by brawner** [comment]
I think I worked out this windows issue. New updates to VS make it pickier than it was a month ago.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10787/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6173/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8780/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10676/)

**Comment by brawner** [comment]
Force pushed a fix for the white space issue. 

[Build Status](http://build.ros2.org/job/Fpr__rosidl_typesupport__ubuntu_focal_amd64/21/)

**Comment by brawner** [comment]
Thank you Scott, for that addition, it really improves this PR significantly.

**Comment by brawner** [comment]
I think this is failed last ngiht:

https://ci.ros2.org/view/nightly/job/nightly_linux_release/lastCompletedBuild/testReport/(root)/projectroot/test_message_type_support/

**Pull request merged**
