### PR TITLE
compare string contents but string pointer addresses.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rmw_fastrtps/issues/742

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@clalancette @sloretz can either of you review this?

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20390/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14801/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21140/)

**Review by quarkytale — APPROVED** [review]
Makes sense to me based on the discussion in the linked issue, not sure why the CI is unstable though.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
> Makes sense to me based on the discussion in the linked issue, not sure why the CI is unstable though.

The unstable CI is currently expected, since we are running things in parallel now and we have a few failing tests.

I'm going to go ahead and merge this one in, thanks @fujitatomoya

**Pull request merged**
