### PR TITLE
[service introspection] Guard `#include <cstddef>` when being included from a `c` source

### PR DESCRIPTION
**Pull request by ihasdapie**
This PR is a prototype for the service introspection REP (https://github.com/ros-infrastructure/rep/pull/360) implementing the proposed single serialized message approach (https://github.com/ros-infrastructure/rep/pull/360#discussion_r902987531).

This PR wraps `#include <cstddef>` in `rosidl_typesupport_c/include/rosidl_typesupport_c/type_support_map.h` so that `rcl` can access `type_support_map_t` 

See: https://github.com/ros2/rcl/pull/990

For instructions on how to build and run this see the meta-ticket https://github.com/ros2/ros2/issues/1285.

Resolves https://github.com/ros2/ros2/issues/1285

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]

**Review by ivanpauno — APPROVED** [review]

**Comment by sloretz** [comment]
@ihasdapie I see this is marked as a draft, but it looks fine as is. Mind if I run CI and merge it?

**Comment by ihasdapie** [comment]
@sloretz  Np, I've just made a CI job for it

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17024/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11584/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17443/)

**Comment by ihasdapie** [comment]
Ignore the previous comment, needed to make a new branch for CI to avoid pulling in my changes in other repos...

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17028/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11588/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17447/)

**Comment by jacobperron** [comment]
@ihasdapie Be careful to use "Resolves #X" in the ticket description only when it should close the connected ticket. Merging this closed the meta-ticket tracking the service introspection work.

**Comment by ihasdapie** [comment]
@jacobperron Got it. I had originally planned on merging them at the same time but in retrospect that might be a bit too hopeful.

**Pull request merged**
