### PR TITLE
Add dependency from Micro DDS

### PR DESCRIPTION
**Pull request by serge-nikulin**
@wjwwood, FYI

### CODE REVIEW

**Comment by serge-nikulin** [comment]
CC: @dejanpan

**Comment by jpsamper2009** [comment]
@wjwwood This shouldn't be needed as long as we add a <member_of_group>, correct?

**Comment by serge-nikulin** [comment]
@wjwwood, if it's as JP says, I'd prefer not to touch this project at all because we will need to rename the Micro module down the road. Please advise.

**Comment by dirk-thomas** [comment]
> This shouldn't be needed as long as we add a <member_of_group>, correct?

Correct. Yes, I think this PR can be closed.

**Pull request closed without merging**
