### PR TITLE
pass macro dep to cppcheck

### PR DESCRIPTION
**Pull request by claireyywang**
part of the effort to pin cppcheck 2.0, ros2/ros2#942
Signed-off-by: claireyywang <22240514+claireyywang@users.noreply.github.com>

### CODE REVIEW

**Comment by claireyywang** [comment]
CI 
linux [Build Status](https://ci.ros2.org/job/ci_linux/11331/)
linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/6569/)
osx [Build Status](https://ci.ros2.org/job/ci_osx/9295/)
windows [Build Status](https://ci.ros2.org/job/ci_windows/11228/)

**Review by sloretz — APPROVED** [review]
@claireyywang mind re-running CI?

**Comment by hidmic** [comment]
@claireyywang ping

**Comment by claireyywang** [comment]
@hidmic sorry about the delay. I'll take a look soon.

**Comment by clalancette** [comment]
Closing this as unnecessary since we mostly don't use cppcheck anymore.

**Pull request closed without merging**
